# Generated by Django 5.2.7 on 2025-10-26 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen_url',
            field=models.URLField(blank=True, default='https://placehold.co/300x300/EBF4FF/6366F1?text=Producto&font=Inter', max_length=500, null=True),
        ),
    ]
